# Curated ge_sim object list. First gcc-clean increment (see cmake/sources.mk).
# Paths are relative to third_party/goldeneye_src.

set(GE_SIM_SOURCES
    src/joy.c
    src/c_data_filler.c
    src/mema.c
    src/stacks.c
    src/debugmenu.c
    src/str.c
    src/rmon.c
    src/usb.c
    src/ramrom.c
    src/token.c
    src/music.c
    src/inflate/inflate.c
    src/game/initnull_0009D0.c
    src/game/math_atan2f.c
    src/game/initnull_000BC0.c
    src/game/rsp.c
    src/game/debugmenu_08FE00.c
    src/game/gun_rodata.c
    src/game/math_unk_05A9E0.c
    src/game/math_floor.c
    src/game/frametiming.c
    src/game/compiletime.c
    src/game/initintromatrices.c
    src/game/bondwalk2.c
    src/game/crc.c
    src/game/mp_music.c
    src/game/mp_weapon.c
    src/game/rle.c
    src/game/quaternion.c
    src/game/game_debug.c
    src/game/music_0D2720.c
    src/game/math_ceil.c
    src/game/null_007970.c
    src/game/blood_decrypt.c
    src/vi.c
    src/memp.c
    src/pi.c
    src/snd.c
)
